In [10]:
#Basic NumPy Array Creation:
# Given input:
import numpy as np
arr = np.zeros((3,3))
arr[1][1]=5
print(arr)

[[0. 0. 0.]
 [0. 5. 0.]
 [0. 0. 0.]]


In [11]:
#Array Reshaping:
# Given input:
arr = np.arange(12)
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
#Element-wise Operations:
# Given input:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
c=a+b
print(c)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [13]:
#Indexing and Slicing:
# Given input:
arr = np.arange(16).reshape(4,4)
second_row = arr[1, :]
third_column = arr[:, 2]
print("Second row:", second_row)
print("Third column:", third_column)

Second row: [4 5 6 7]
Third column: [ 2  6 10 14]


In [15]:
#Boolean Masking:
# Given input output an array containing values of array arr that are > 10:
arr = np.array([5, 15, 25, 10])
arr1=arr[arr>10]
print(arr1)
# Desired output:
# array([15, 25])

[15 25]


In [16]:
#Stacking Arrays:
# Given input:
a = np.array([1,2,3])
b = np.array([4,5,6])
# Horizontal stacking
horizontal_stack = np.hstack((a, b))
# Vertical stacking
vertical_stack = np.vstack((a, b))
print("Horizontal stack:\n", horizontal_stack)
print("Vertical stack:\n", vertical_stack)


Horizontal stack:
 [1 2 3 4 5 6]
Vertical stack:
 [[1 2 3]
 [4 5 6]]


In [17]:
#Broadcasting:
# Given input:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([1,2,3])
result=a*b
print(result)


[[ 1  4  9]
 [ 4 10 18]]


In [18]:
#Matrix Transposition:
# Given input:
arr = np.arange(15).reshape(5,3)
transposed_arr = arr.T
print(transposed_arr)

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


In [19]:

#Dot Product:
# Given input:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
result=np.dot(a,b)
print(result)

[[19 22]
 [43 50]]


In [20]:

#Mean and Standard Deviation:
# Given input:
arr = np.array([1, 2, 3, 4, 5])
arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
std_value = np.std(arr)

print("Mean:", mean_value)
print("Standard deviation:", round(std_value, 3))

Mean: 3.0
Standard deviation: 1.414


In [22]:
# Question 1: Create a 5x5 NumPy array filled with zeros.
a=np.zeros((5,5))
print(a)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
# Question 2: Create a 3x3 NumPy array filled with ones.
b=np.ones((3,3));
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# Question 3: Create a 4x4 identity matrix using NumPy.
c=np.identity(4)
print(c)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
 #Question 4: Create a 2D NumPy array of shape (5, 5) with random values between 0 and 1.
arr=np.random.rand(5,5)
print(arr)


[[0.34976998 0.00916953 0.33351499 0.56748175 0.46000138]
 [0.23524592 0.81152548 0.79095028 0.42046076 0.59548768]
 [0.83311187 0.79040687 0.73713099 0.53374534 0.93783324]
 [0.38835018 0.87915736 0.16329563 0.50673673 0.91044406]
 [0.7498333  0.75355226 0.70677297 0.34784138 0.29716456]]


In [31]:
# Question 5: Create a 1D NumPy array of 10 elements with values ranging from 0 to 9.
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
# Question 6: Reshape a 1D array of 16 elements into a 4x4 2D array.
arr=np.arange(16)
arr1=arr.reshape(4,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [33]:
# Question 7: Flatten a 3x3 NumPy array into a 1D array.
arr=np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
# Flatten the array into 1D
arr1=arr.flatten()
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [36]:
# Question 8: Extract the second row from a 4x4 NumPy array.
arr = np.arange(16).reshape(4,4)
second_row = arr[1, :]
print("Second row:", second_row)

Second row: [4 5 6 7]


In [37]:
# Question 9: Extract the third column from a 5x5 NumPy array.
arr = np.arange(25).reshape(5,5)
third_column = arr[:, 2]
print("Third column:", third_column)

Third column: [ 2  7 12 17 22]


In [38]:
# Question 10: Replace all values greater than 5 in a NumPy array with 0.
array=np.array([[1, 2, 6],
                [7, 3, 4],
                [5, 8, 9]])
# Replace values greater than 5 with 0
array[array > 5]=0
print(array)

[[1 2 0]
 [0 3 4]
 [5 0 0]]


In [40]:
# Question 11: Add two 3x3 NumPy arrays element-wise.
a=np.full((3, 3), 5)
b=np.full((3, 3), 5)
c=a+b
print(c)

# Desired Output:
# [[10 10 10]
#  [10 10 10]
#  [10 10 10]]

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [42]:
# Question 12: Multiply a 2x2 NumPy array by a scalar value (e.g., 2).
arr=np.array([[1, 2],
              [3, 4]])
arr1=arr*2
print(arr1)
# Desired Output:
# [[ 2  4]
#  [ 6  8]]

[[2 4]
 [6 8]]


In [43]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
result = np.dot(a, b)
print(result)

[[19 22]
 [43 50]]


In [45]:

# Question 14: Find the maximum value in a 3x3 NumPy array.
a=np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
maxm=np.max(a)
print(maxm)
# Desired Output:
# 9

# Question 15: Compute the mean of all values in a 4x4 NumPy array.
b=np.arange(16).reshape(4, 4)
avg=np.mean(b)
print(avg)
# Desired Output:
# 7.5

9
7.5


In [46]:
# Question 16: Create a 5x5 2D array with random integer values between 0 and 255.
a=np.random.randint(0, 256, (5, 5))
print(a)


[[120 207  76  60 183]
 [ 90 215 200  54  44]
 [162  62 158 101 194]
 [ 50  25 209 123  75]
 [171 212 215  37  36]]


In [47]:
# Question 17: Normalize a 5x5 2D array so that all values are between 0 and 1.
array=np.random.randint(0, 256, (5, 5))
b= (array - array.min()) / (array.max() - array.min())
print(b)

[[0.42857143 0.11059908 0.24884793 0.01382488 0.99539171]
 [0.7235023  0.70046083 0.62211982 0.38248848 0.44239631]
 [0.11520737 0.18894009 0.08294931 0.         0.20276498]
 [0.07834101 0.80184332 0.04147465 0.23963134 0.70046083]
 [1.         0.60368664 0.34101382 1.         0.89861751]]


In [50]:
# Question 18: Convert a 5x5 2D array to a binary array by setting values > 128 to 255 and others to 0.
a=np.random.randint(0, 256, (5, 5))
b=np.where(a> 128, 255, 0)
print(a)
print(b)


[[215  48 177 247  40]
 [229  16 222  45  70]
 [237  42  83 132 175]
 [201 133  56  96  97]
 [ 90  53 112 158 126]]
[[255   0 255 255   0]
 [255   0 255   0   0]
 [255   0   0 255 255]
 [255 255   0   0   0]
 [  0   0   0 255   0]]


In [52]:
# Question 19: Flip a 3x3 2D array horizontally.
a=np.arange(1,10).reshape(3,3)
b= a[:, ::-1]
print(b)



[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [54]:
# Question 20: Rotate a 3x3 2D array by 90 degrees clockwise.
a=np.arange(1,10).reshape(3,3)
b=np.rot90(a,k=-1)
print(b)

[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [55]:
# Question 21: Create a 3D array of shape (5, 5, 3) with random integer values between 0 and 255.
# Desired Output: (Random values, example)

a=np.random.randint(0,255,(5,5,3))
print(a)

[[[253 228  19]
  [147  61 197]
  [ 26 252 239]
  [205 229 122]
  [ 57 223 201]]

 [[190 153 116]
  [ 71 150 126]
  [ 58  87   7]
  [253 221  37]
  [127  43  39]]

 [[ 92 231  50]
  [ 34 157 163]
  [ 85   8 152]
  [183  93 184]
  [110  68 198]]

 [[ 29 193 188]
  [ 77   6 226]
  [165 176 142]
  [109  99 138]
  [ 99 220 233]]

 [[186  59 198]
  [ 80 125 113]
  [240  95 216]
  [ 81  45  58]
  [ 25 234 148]]]


In [57]:
# Question 22: Extract the first channel from a 5x5x3 3D array.
a=np.random.randint(0,255,(5,5,3))
first_c=a[:,:,0]
print(first_c)

[[207 135 154 122 205]
 [194 209   8  88  51]
 [133 242 177 130 156]
 [ 32 195 245 249 112]
 [206  34 143  55 206]]


In [68]:
# Question 23: Swap the second and third channels of a 5x5x3 3D array.
a=np.random.randint(0,255,(5,5,3))
swapped_channels=a[:, :, [0, 2, 1]]
print(swapped_channels)


[[[ 25 115 120]
  [115  31  46]
  [137 168  71]
  [216 149  89]
  [ 47 111 230]]

 [[125 245 230]
  [244 250 222]
  [171  62  64]
  [249 249 112]
  [ 95  59  31]]

 [[ 95  96  78]
  [129 148 180]
  [ 17 168  15]
  [ 30  95 213]
  [ 15 147 140]]

 [[220 218  77]
  [  5 179  51]
  [ 72  67 106]
  [ 85  82  98]
  [222 189 169]]

 [[ 77 125  68]
  [194 223  10]
  [139 174 123]
  [135  30 228]
  [ 10 116  45]]]


In [64]:
# Question 24: Apply a smoothing operation to a 5x5 2D array using a 3x3 kernel.
from scipy.ndimage import convolve
array_2d = np.random.randint(0, 256, (5, 5))
kernel = np.ones((3, 3)) / 9
smoothed_array = convolve(array_2d, kernel, mode='constant', cval=0)

print("Original Array:\n", array_2d)
print("\nSmoothed Array:\n", smoothed_array)

Original Array:
 [[ 42  17 187  76  46]
 [237 128 232 110 208]
 [ 61 225 181 121  34]
 [196  17 253 151 174]
 [157 240 191 226 197]]

Smoothed Array:
 [[ 47  93  83  95  48]
 [ 78 145 141 132  66]
 [ 96 170 157 162  88]
 [ 99 169 178 169 100]
 [ 67 117 119 132  83]]


In [66]:
# Question 25: Resize a 4x4 2D array to 8x8 using nearest-neighbor interpolation.
array = np.arange(16).reshape(4, 4)
resized_array = np.repeat(np.repeat(array, 2, axis=0), 2, axis=1)
print(resized_array)

[[ 0  0  1  1  2  2  3  3]
 [ 0  0  1  1  2  2  3  3]
 [ 4  4  5  5  6  6  7  7]
 [ 4  4  5  5  6  6  7  7]
 [ 8  8  9  9 10 10 11 11]
 [ 8  8  9  9 10 10 11 11]
 [12 12 13 13 14 14 15 15]
 [12 12 13 13 14 14 15 15]]
